-- DropIndex
DROP INDEX "Rating_matchId_raterId_key";

-- AlterTable
ALTER TABLE "Notification" ADD COLUMN     "occurrenceDate" TIMESTAMP(3);

-- AlterTable: add nullable first, backfill, then enforce NOT NULL — the
-- straight NOT NULL add generated by schema diffing fails against any
-- existing row (there is one in this dev DB), so existing ratings are
-- backfilled from the calendar date of their match's trip's departureTime
-- (a ONE_TIME trip only ever had one occurrence, so this is exactly the
-- value that trip's rating was actually for).
ALTER TABLE "Rating" ADD COLUMN     "occurrenceDate" TIMESTAMP(3);

UPDATE "Rating" r
SET "occurrenceDate" = date_trunc('day', t."departureTime")
FROM "Match" m
JOIN "Trip" t ON t.id = m."tripId"
WHERE r."matchId" = m.id;

ALTER TABLE "Rating" ALTER COLUMN "occurrenceDate" SET NOT NULL;

-- CreateIndex
CREATE UNIQUE INDEX "Rating_matchId_raterId_occurrenceDate_key" ON "Rating"("matchId", "raterId", "occurrenceDate");
